### ISSUE TITLE
Plans for this tool

### ISSUE THREAD

**Issue by T3sT3ro** [pema99/UnityShaderParser#1]
Hi, I've been looking for some tool that can handle both hlsl and shaderlab for some time, and was especially interested in something like Roslyn's syntax API for creating and modifying syntax trees. I've seen tgjones' hlslTools repo and asked if it's possible in there, but an API like that wasn't present in his project. I also wanted something that I could quite easily add to a unity package, because I am writing a Hlsl+Shaderlab shader generator editor package for unity for some time now, so I am fairly interested in what you got there! I have some questions regarding you project here:

Do you plan on extending this tool with things like syntax rewritters, syntax factories/builders and possibly other things that can be used to work with ASTs by creating them in code without parsing? What subset of those things is already possible? 

Do you plan on using immutable or mutable ASTs? I've seen syntax nodes generally follow the `Property {get; set;}` pattern, so I assume you are most probably designing with mutability in mind?

I didn't have yet much time to check what your tool's capabilities are and I am currently working on a syntax api for hlsl and shaderlab myself (without the parser, I already have some successes in generating ASTs from code), so this tool is currently in my area of interest, and if it were to support those operation I could consider migrating from my prototype grade lib to yours.

What C# version are you aiming for? I can assume that if you wrote specifically UnityShaderParser you target (unity supported subset of) C#8/C#9.

Do you plan to release this as a unity package?

Do you plan on migrating some of the boilerplate code (e.g. acceptor methods, `GetChildren` calls) to roslyn source generators? In my case I use them fairly successfully and they can considerably reduce the boilerplate!

Do you plan on adding some tools like basic formatters, AST normalizers and AST validators?

Do you plan to include some higher level APIs, like Symbol API, Binding API or Flow Analysis as well?

Lastly, do you have some kind of TODO list / roadmap / ticket list of things you want to add, what this tool you want to be and what you DON'T want it to be?

**Comment by pema99** [comment]
Hello.

> Do you plan on extending this tool with things like syntax rewritters, syntax factories/builders and possibly other things that can be used to work with ASTs by creating them in code without parsing? What subset of those things is already possible?

The library currently has these capabilities:
- Preprocessor with multiple modes
  - Full expansion
  - Expansion of #include only
  - Expansion of everything _but_ #include
  - Simply stripping directives from source code
  - Do nothing - in this case, the directives are represented directly in the AST instead. Only works for sufficiently simply directives.
- ShaderLab lexing & parsing (optionally including parsing the HLSL code embedded within)
- HLSL lexing & parsing
- A reusable Visitor pattern implementation for both the HLSL and ShaderLab syntax trees
- A pretty printer / formatter for HLSL (doesn't handle trivia such as comments, though)
- Some helper classes for the common case where you want to walk the syntax tree and make textual replacements (called HLSLEditor and ShaderLabEditor in the code)
- The types making up the syntax trees are simple enough that you could build them manually from code.

I'm not sure how much of that overlaps with Roslyn, and what isn't covered. I'm not particularly interested in anything more than that, since I don't have a use for it. The one "missing" thing is a pretty printer for ShaderLab, to match the existing one for HLSL. I'll probably get around to it some point.

> Do you plan on using immutable or mutable ASTs? I've seen syntax nodes generally follow the Property {get; set;} pattern, so I assume you are most probably designing with mutability in mind?

Everything in the ASTs that can be mutable is made mutable. That won't change. This may be seen as less clean, and I generally treat syntax nodes as immutable, but I don't want to exclude potential use cases just in the name of cleanliness. This lets you do stuff like grabbing an AST node, making a small edit to it, and pretty printing just that one edited node, etc. The library itself doesn't mutate nodes at any point, though.

> What C# version are you aiming for? I can assume that if you wrote specifically UnityShaderParser you target (unity supported subset of) C#8/C#9.

It's backwards compatible to C# 7.3 and will stay like that. No features from after that language version are used (this is enforced). That's the version of C# used by Unity 2019.3. 

> Do you plan to release this as a unity package?

I don't have any particular plans distribution. Right now I'm distributing as a zip with the source, and as a single merged `.cs` file. Since there are 0 dependencies, you can just drop that one `.cs` file into your own Unity project to use the library, or vendor it as a simple dependency. I'm not opposed to other setups, I just haven't bothered setting anything up since I'm not great with CI.

> Do you plan on migrating some of the boilerplate code (e.g. acceptor methods, GetChildren calls) to roslyn source generators? In my case I use them fairly successfully and they can considerably reduce the boilerplate!

No. The boilerplate is admittedly a bit cumbersome, but it's quite intentional. One hard goal of the project was to have absolutely 0 dependencies and 0 code generation - that's not going to change. In my experience source generators can complicate some use cases, and aren't something I like to use unless the boilerplate is absolutely insurmountable.

> Do you plan on adding some tools like basic formatters, AST normalizers and AST validators?

There's a pretty printer for HLSL as mentioned earlier, and I want to add one for ShaderLab. I'm not interested in adding any additional kind of semantic analysis.

> Do you plan to include some higher level APIs, like Symbol API, Binding API or Flow Analysis as well?

No.

> Lastly, do you have some kind of TODO list / roadmap / ticket list of things you want to add, what this tool you want to be and what you DON'T want it to be?

No. It's developed quite sporadically in my spare time mostly as something I've found the need for in personal projects. I open sourced it since I figured others might find it useful. I'd say the library is generally in a usable state though, considering what my goals for it were.

**Comment by pema99** [comment]
You might additionally be interested in some example code. So far I know of 2 uses of the API. 

One of them is my own WIP for integrating the Slang shading language into Unity. I use the library both for parsing ShaderLab and substituting code blocks, as well parsing the HLSL output of the Slang compiler and doing some transformations on it to make it Unity-compatible. https://github.com/pema99/SlangUnityPlugin/blob/master/dev.pema.slang-shader-plugin/Editor/Scripts/SlangShaderImporter.cs#L38-L352

Another is a friend on mine making a modular  system for quickly generating shaders, similar to surface shaders (https://shaders.orels.sh/). They use the library for some more detailed analysis of shadercode than what Unity can provide:  https://github.com/orels1/orels-Unity-Shaders/pull/65

**Comment by pema99** [comment]
Finally I'll mention that I'm open to contributions. It's also permissively licensed, so y'know, you can do whatever you want with it. I'm mostly doing bugfixes and minor changes at this point, since I've reached most of the personal goals I had for the project already. If bug reports come in, I'll spend some time here and there to address them, but for anything more like a feature request, I'm not going to put in the work, unless it is something I happen to find a use for myself.

**Comment by T3sT3ro** [comment]
Pretty nice, thanks for your time to answer and for this library!
